spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tournament?currentSchema=rt
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    type: org.postgresql.ds.PGSimpleDataSource

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creatin: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
        ddl-auto: update